### ISSUE TITLE
Can't find serial port on OSX

### ISSUE THREAD

**Issue by mechatronicsguy** [arachnidlabs/tsunami-arduino#2]
Just got my red tsunami in the post. After following the steps here:
https://github.com/arachnidlabs/tsunami-arduino/wiki/Installation

and plugging it in, no serial port shows up. After running 'sudo dmesg' it yields this:
USBF:    585.242    The IOUSBFamily is having trouble enumerating a USB device that has been plugged in.  It will keep retrying.  (Port 5 of Hub at 0x14000000)
USBF:    590.634    The IOUSBFamily was not able to enumerate a device.
USBF:    591.486    The IOUSBFamily is having trouble enumerating a USB device that has been plugged in.  It will keep retrying.  (Port 5 of Hub at 0x14000000)
USBF:    594.972    The IOUSBFamily was not able to enumerate a device.
USBF:    595.827    The IOUSBFamily is having trouble enumerating a USB device that has been plugged in.  It will keep retrying.  (Port 5 of Hub at 0x14000000)
USBF:    596.681    The IOUSBFamily gave up enumerating a USB device after 10 retries.  (Port 5 of Hub at 0x14000000)
USBF:    596.681    The IOUSBFamily was not able to enumerate a device.

**Comment by Arachnid** [comment]
That's very odd. Are you able to try plugging it in to another computer to see if you can get it working there? That'll let us track down if it's a hardware issue with the Tsunami, or a software one on your mac.

**Comment by mechatronicsguy** [comment]
Solved. Turned out to be a dodgy USB cable. After changing it instantly finds the port every time. The bad cable would work perhaps one time in five.
