### ISSUE TITLE
Cannot find Windows Driver

### ISSUE THREAD

**Issue by syberphunk** [arachnidlabs/tsunami-arduino#3]
I'm using Windows 7 64bit.
I've downloaded the Arduino IDE, which is currently 1.6.5 r2.
Even after extracting the 'old arduino drivers' zip file, and pointing Windows at the Arduino / sketchbook folder, and looking at the steps here : https://github.com/arachnidlabs/tsunami-arduino/wiki/Tutorials 

Windows cannot find the driver, all I can find in the tutorials is a link to a json file.

**Comment by Arachnid** [comment]
I'm not sure what the "old arduino drivers" zip file is; you need to look in "packages/arachnidlabs/hardware/avr/1.0.0/driver" under your Arduino sketchbook folder, as the tutorial says.

**Comment by syberphunk** [comment]
Sorry, but I'm not finding that folder path on Windows, it does not appear to come with the Arduino IDE and it is not in your repo.
The zip file I'm referring to is:
"C:\Program Files (x86)\Arduino\drivers\Old_Arduino_Drivers.zip"
Though that also does not have the driver in it.

**Comment by Arachnid** [comment]
It doesn't come with the Arduino IDE; it will have been installed if you followed the steps earlier in the tutorial to install the Tsunami board and libraries. You should be looking in your Sketchbook folder, off "Documents" or "My Documents" or your home directory (Depending on platform), not in the Arduino install folder.

**Comment by syberphunk** [comment]
You're saying that the driver is downloaded as part of the board definition with the json by the Arduino IDE?
If that's the case, that wasn't clear to me from reading the steps.

**Comment by Arachnid** [comment]
Yes, that's correct. The tutorial says "Windows requires drivers in order to interact with the Tsunami. These were included in the hardware definitions you downloaded in the previous steps; you just need to tell Windows how to find them."

I'll see if I can make that clearer; suggestions are welcome.

**Comment by syberphunk** [comment]
Thanks.
Is it possible to have an alternative method of acquiring the definitions / drivers? Or possibly a mirror?
I ask because the internet connection I'm using is causing timeouts / partial downloads / it is very slow with this method.

**Comment by Arachnid** [comment]
The files are in this repository: https://github.com/arachnidlabs/arachnidlabs-boards/tree/master/driver - but you won't be able to actually do anything with the Tsunami until you have valid board definitions anyway!

**Comment by syberphunk** [comment]
Hm.
So the Arduino IDE now knows what a Tsunami is and appears in the board list. However, the files haven't appeared in my sketchbook to be able to install the driver.
Searching the computer for the file(s) show they aren't on the machine. Though how much we trust windows search function is debatable.

**Comment by syberphunk** [comment]
I found it using a different search tool.
So the reason why it didn't appear in Windows Search was because it's in a hidden folder.

c:\users\WINDOWSUSERNAME\appdata\roaming\arduino15\

It does not save it into the sketchbook at all, it puts it into the appdata\roaming<arduino version> folder of your Windows user profile.

So the full path is:

C:\Users\WINDOWSUSERNAME\AppData\Roaming\Arduino15\packages\arachnidlabs\hardware\avr\1.0.0\driver

The driver also throws up a warning asking if you want to install it anyway, which we of course want to do. The device also identifies as just 'Tsunami' before driver installation.

You may wish to update your installation guide. You can close this issue.

Thanks.

**Comment by Arachnid** [comment]
Wow, okay. That's not what I got when I tested it; evidently Arduino behaves differently on different Windows installs. I'll update the guide accordingly, probably to simply instruct people to redownload it from the repo.

Thanks for the feedback!
